function bancadasuperiorcajatitracesVG7065 = importfileCSV(filename, dataLines)
%IMPORTFILE Import data from a text file
%  BANCADASUPERIORCAJATITRACESVG7065 = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the
%  numeric data.
%
%  BANCADASUPERIORCAJATITRACESVG7065 = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  bancadasuperiorcajatitracesVG7065 = importfile("G:\Meu Drive\Workana\Andamento\Marilia - Doutorado - Processamente Cloud Point e ANN\Cajati\bancada superior cajati_traces_VG-70-65.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 10-Aug-2020 10:15:08

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = [",",";"];

% Specify column names and types
opts.VariableNames = ["Var1", "Trace_id", "Point_id", "Start_x", "Start_y", "Start_z", "End_x", "End_y", "End_z", "Cost", "Cost_Mode"];
opts.SelectedVariableNames = ["Trace_id", "Point_id", "Start_x", "Start_y", "Start_z", "End_x", "End_y", "End_z", "Cost", "Cost_Mode"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");

% Import the data
bancadasuperiorcajatitracesVG7065 = readtable(filename, opts);

%% Convert to output type
bancadasuperiorcajatitracesVG7065 = table2array(bancadasuperiorcajatitracesVG7065);
end